name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify SSH connection
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} echo "SSH connection successful"

      - name: Build Docker image
        run: docker build -t backend-cm:latest .
        working-directory: /canchamanager  # Reemplaza con la ruta correcta donde está tu Dockerfile



      - name: Copy files to remote server
        run: scp -r ./* root@${{ secrets.SERVER_IP }}:/canchamanager
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}

      - name: SSH into remote server and restart application
        run: |
          ssh root@${SERVER_IP} 'cd /canchamanager && docker-compose down && docker-compose up -d'
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
