name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check if container exists
        run: |
          CONTAINER_EXISTS=$(ssh root@${{ secrets.SERVER_IP }} 'docker ps -aqf "name=canchamanager-app"')
          echo "::set-output name=exists::${CONTAINER_EXISTS}"

      - name: Stop and remove existing Docker container
        run: |
          ssh root@${{ secrets.SERVER_IP }} 'docker stop canchamanager-app || true'
          ssh root@${{ secrets.SERVER_IP }} 'docker rm canchamanager-app || true'

      - name: Remove existing Docker image
        run: |
          ssh root@${{ secrets.SERVER_IP }} 'docker rmi canchamanager-app:latest || true'

      - name: Send Docker image to Linux Server
        run: docker save canchamanager-app:latest | ssh root@${{ secrets.SERVER_IP }} 'docker load'

      - name: Restart Docker container
        run: |
          ssh root@${{ secrets.SERVER_IP }} 'docker run -d --name canchamanager-app -p 8080:8080 canchamanager-app:latest'
