name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key to known_hosts
        run: ssh-keyscan -t rsa ${SERVER_IP} >> ~/.ssh/known_hosts
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}

      - name: Copy files to remote server
        run: scp -r ./* root@${SERVER_IP}:/canchamanager
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}

      - name: SSH into remote server and restart application
        run: |
          ssh root@${SERVER_IP} 'cd /canchamanager && docker-compose down && docker-compose up -d'
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
