name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -p 22 <GitHub_IP> >> ~/.ssh/known_hosts
          ssh -v root@${{ secrets.SERVER_IP }} pwd  # Verifica la conexión SSH para depurar problemas de autenticación

      - name: Copy files to server
        run: |
          scp -r ./* root@${{ secrets.SERVER_IP }}:/canchamanager

      - name: SSH into server and deploy Docker container
        run: |
          ssh -v root@${{ secrets.SERVER_IP }} 'cd /canchamanager && docker-compose down'
          ssh -v root@${{ secrets.SERVER_IP }} 'cd /canchamanager && docker-compose up -d'
